### ISSUE TITLE
queue feature

### ISSUE THREAD

**Issue by kafisatz** [TrimVis/butlarr#11]
Thanks for putting this together.
I like the queue feature.
Is it correct that the queue will only display series requested by the user?
I wonder if, for the ADMIN user, the queue could display the entire queue in sonarr/radarr?

**Comment by TrimVis** [comment]
The queue should be shared across users.
Sonarr and Radarr do not have a user system afaik and therefore there is only one centralized queue shared by everyone accessing the instance
