### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8)

### ISSUE THREAD

**Issue by afpfernandes** [TrimVis/butlarr#21]
After running:
```
docker run -it -e BUTLARR_INTERACTIVE_SETUP=true trimforce/butlarr:latest
```
I get:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /usr/local/bin/entrypoint.sh: exec format error
```

**Comment by TrimVis** [comment]
Are you running this on a M1 Mac or any other Arm based system by chance?

If so try adding `--platform linux/amd64` to the run command.

So something like this:
`docker run --platform linux/amd64 -it -e BUTLARR_INTERACTIVE_SETUP=true trimforce/butlarr:latest`

**Comment by afpfernandes** [comment]
I am running on a raspberry pi 5. I tried your command but now I get:

```
Status: Downloaded newer image for trimforce/butlarr:latest
exec /usr/local/bin/entrypoint.sh: exec format error
```

**Comment by TrimVis** [comment]
This issue is likely happening because the docker container has been built on a x86 system but you are trying to use it on a Arm system.

It seems like its necessary to use buildKit during my builds to get it working on Arm too.
I will need to look into this.

For now I would recommend you to do the manual setup, that should work without issues on ARM systems.
I can also help you through it in case you encounter any issues.

**Comment by TrimVis** [comment]
I recommend you to try the `Quick Local Setup` first (see Readme) and see if that works.

**Comment by ShrirajHegde** [comment]
@TrimVis Please build and push the images for linux/amd64.

Multi-arch images are the norm now. 

Edit: I have made a pull request implementing the workflow for multi arch image. Please review, merge and trigger a release.

**Comment by TrimVis** [comment]
Thanks to @ShrirajHegde we now have docker images built for arm :partying_face: 
Therefore by simply pulling and trying again this issue should be resolved

**Comment by afpfernandes** [comment]
Can confirm it now works. Thanks!
